(function(){
  'use strict';
  var $=function(s){return document.querySelector(s);};
  var $$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s));};
  var save=CRStorage.load();
  var state={stageId:1,capacity:4,tubes:[],initialTubes:[],rules:{},ruleState:{locksOpen:true,chainIndex:0,flipsRemaining:0,flipsUsed:0,isFlipped:false,forgeRemaining:0,dyesUsed:0,dyeUsed:{},serveProgress:[]},initialRuleState:{locksOpen:true,chainIndex:0,flipsRemaining:0,flipsUsed:0,isFlipped:false,forgeRemaining:0,dyesUsed:0,dyeUsed:{},serveProgress:[]},moveLimit:null,selectedTube:null,moveCount:0,history:[],isAnimating:false,isChoosingDye:false,isCleared:false,isStuck:false,isLimitFailed:false};
  var app=window.ColorRestore={save:save,state:state};
  var screens=$$('.screen'),board=$('#tube-board'),tutorialStep=0,hintTimer,solveTimer,solveGeneration=0;

  function show(id){screens.forEach(function(x){x.classList.toggle('active',x.id===id);});window.scrollTo(0,0);}
  function persist(){CRStorage.save(save);}
  function worldCompletion(world){return CRStage.completion(world,save.clearedStages,CR_STAGES.length);}
  function buildSelect(){
    var worlds=CRStage.worlds(CR_STAGES.length);
    $('#world-tabs').innerHTML=worlds.map(function(w){var done=worldCompletion(w);return '<button data-start="'+w.start+'">'+w.label+'<small>'+done.count+'/'+done.total+'</small></button>';}).join('');
    var html='';
    CR_STAGES.forEach(function(s){var locked=s.id>save.unlockedStage,done=save.clearedStages.indexOf(s.id)>=0;html+='<button class="stage-tile '+(locked?'locked ':'')+(done?'done':'')+'" data-stage="'+s.id+'" '+(locked?'disabled':'')+'><span>'+(locked?'🔒':s.id)+'</span><small>'+(done?'BEST '+save.bestMoves[s.id]:locked?'LOCKED':'PLAY')+'</small></button>';});
    $('#stage-grid').innerHTML=html;
    $$('.stage-tile:not(.locked)').forEach(function(b){b.onclick=function(){loadStage(+b.dataset.stage);};});
    $$('#world-tabs button').forEach(function(b){b.onclick=function(){var tile=$('[data-stage="'+b.dataset.start+'"]');if(tile)tile.scrollIntoView({behavior:'smooth',block:'center'});};});
  }
  function cancelSolve(){solveGeneration++;clearTimeout(solveTimer);}
  function clearHint(){clearTimeout(hintTimer);$$('.hint-from,.hint-to,.hint-forge,.hint-serve,.portal-line.active').forEach(function(el){el.classList.remove('hint-from','hint-to','hint-forge','hint-serve','active');});}
  function closeForgePicker(){state.isChoosingDye=false;var picker=$('#forge-picker'),button=$('#forge-btn'),options=$('#forge-options');if(picker)picker.classList.add('hidden');if(button)button.setAttribute('aria-expanded','false');if(options)options.innerHTML='';}
  function cancelWork(){cancelSolve();clearHint();closeForgePicker();}
  function colorName(color){return {red:'赤',blue:'青',yellow:'黄',green:'緑',purple:'紫',orange:'橙',cyan:'水',pink:'桃',gray:'無色'}[color]||color;}
  function serveBatches(lane){return lane?[lane.initial].concat(lane.queue||[]):[];}
  function collectServeEvents(before){var events=[],lanes=CRGame.serveLanes(state.rules);lanes.forEach(function(lane,laneIndex){var batches=serveBatches(lane),start=before&&Number.isInteger(before[laneIndex])?before[laneIndex]:0,end=state.ruleState.serveProgress&&state.ruleState.serveProgress[laneIndex]||0;for(var served=start;served<end;served++)events.push({laneIndex:laneIndex,tube:lane.tube,symbol:lane.symbol||String.fromCharCode(65+laneIndex),batch:batches[served],arrival:batches[served+1]||null,served:served+1,total:batches.length});});return events;}
  function serveEventText(event){return '📦 DOCK '+event.symbol+' '+colorName(event.batch.target)+'を出荷'+(event.arrival?'・次便 '+colorName(event.arrival.target)+'が到着':'・全便完了');}
  function addServeBatch(parent,batch,label,current){var item=document.createElement('div'),tag=document.createElement('small'),title=document.createElement('b'),load=document.createElement('span'),names=document.createElement('em');item.className='serve-batch'+(current?' current':'');tag.textContent=label;title.textContent='注文 '+colorName(batch.target);load.className='serve-load';batch.balls.forEach(function(color){var ball=document.createElement('i');ball.className='serve-mini '+color;ball.setAttribute('aria-hidden','true');load.appendChild(ball);});names.textContent='積荷 '+(batch.balls.length?batch.balls.map(colorName).join('・'):'空');item.appendChild(tag);item.appendChild(title);item.appendChild(load);item.appendChild(names);parent.appendChild(item);}
  function renderServeQueue(){var area=$('#serve-area'),lanes=CRGame.serveLanes(state.rules);area.innerHTML='';if(!lanes.length){area.classList.add('hidden');return;}area.classList.remove('hidden');lanes.forEach(function(_,laneIndex){var status=CRGame.serveStatus(state.rules,state.ruleState,laneIndex),card=document.createElement('section'),head=document.createElement('div'),title=document.createElement('b'),progress=document.createElement('span'),flow=document.createElement('div');card.className='serve-lane'+(status.current?'':' done');card.dataset.laneIndex=laneIndex;head.className='serve-lane-head';title.textContent='📦 DOCK '+status.symbol;progress.textContent='出荷 '+status.served+'/'+status.total;head.appendChild(title);head.appendChild(progress);flow.className='serve-flow';if(status.current)addServeBatch(flow,status.current,'NOW',true);status.waiting.forEach(function(batch,index){var arrow=document.createElement('strong');arrow.className='serve-arrow';arrow.textContent='›';arrow.setAttribute('aria-hidden','true');flow.appendChild(arrow);addServeBatch(flow,batch,'NEXT '+(index+1),false);});if(!status.current){var done=document.createElement('div');done.className='serve-all-done';done.textContent='✓ ALL SERVED';flow.appendChild(done);}else if(!status.waiting.length){var empty=document.createElement('span');empty.className='serve-next-empty';empty.textContent='NEXT —';flow.appendChild(empty);}card.setAttribute('aria-label','ドック'+status.symbol+'、出荷'+status.served+'/'+status.total+(status.current?'、現在の注文'+colorName(status.current.target):'、全便完了'));card.appendChild(head);card.appendChild(flow);area.appendChild(card);});}
  function animateServeEvents(events){var first=null;events.forEach(function(event){var tube=board.children[event.tube],lane=$('.serve-lane[data-lane-index="'+event.laneIndex+'"]');if(tube){tube.classList.add('serve-arriving');if(!first)first=tube;}if(lane)lane.classList.add('serve-event');});return first;}
  function clearServeEvents(events){events.forEach(function(event){var tube=board.children[event.tube],lane=$('.serve-lane[data-lane-index="'+event.laneIndex+'"]');if(tube)tube.classList.remove('serve-arriving');if(lane)lane.classList.remove('serve-event');});}
  function stageRuleLabel(data){
    var portals=CRGame.portalPairs(data.rules),portalLabel=portals.length?'◉ PORTAL '+portals.map(function(pair,index){return pair.symbol||String.fromCharCode(65+index);}).join('・'):'';
    var forge=data.rules&&data.rules.forgeLimit||0,needs=forge?CRGame.dyeNeeds(state.tubes,state.rules):{},needColors=Object.keys(needs),forgeLabel=forge?'⚗ FORGE 残り'+state.ruleState.forgeRemaining+'/'+forge+(needColors.length?'・必要 '+needColors.map(function(color){return colorName(color)+'×'+needs[color];}).join(' '):'・配色完了'):'';
    var lanes=CRGame.serveLanes(data.rules),serveLabel=lanes.length?'📦 SERVE '+CRGame.servedCount(data.rules,state.ruleState)+'/'+CRGame.serveTotal(data.rules):'',flip=data.rules&&data.rules.flipLimit||0,flipLabel=flip?'↕ FLIP 残り'+state.ruleState.flipsRemaining+'/'+flip+'・SIDE '+(state.ruleState.isFlipped?'B':'A'):'',special=[serveLabel,portalLabel,forgeLabel,flipLabel].filter(Boolean).join('・');
    var chain=data.rules&&data.rules.unlockChain||[];
    if(chain.length){var index=Math.min(chain.length,state.ruleState.chainIndex||0);return [special,index===chain.length?'🔗 連鎖 '+index+'/'+chain.length+' 完了':'🔗 連鎖 '+index+'/'+chain.length+'・'+colorName(chain[index].color)+'完成で筒'+(chain[index].tube+1)+'解放'].filter(Boolean).join('・');}
    if(data.moveLimit)return [special,'⏱ '+data.moveLimit+'手以内'].filter(Boolean).join('・');
    if(data.rules&&data.rules.targets)return [special,'🎯 指定色を目標チューブへ'].filter(Boolean).join('・');
    if(data.rules&&data.rules.lockedTubes)return [special,'🔒 1色完成でチューブ解放'].filter(Boolean).join('・');
    if(special)return special;
    if((data.capacity||4)===5)return '5 BALL TUBES';
    if(data.tubes.filter(function(t){return !t.length;}).length===1)return 'EMPTY TUBE ×1';
    return '';
  }
  function currentKey(){return CRGame.stateKey(state.tubes,state.capacity,state.rules,state.ruleState);}
  function searchOptions(maxVisited){return {maxVisited:maxVisited,rules:state.rules,ruleState:CRGame.cloneRuleState(state.ruleState)};}
  function loadStage(id){
    var data=CR_STAGES[id-1];if(!data||id>save.unlockedStage)return;
    cancelWork();state.stageId=id;state.capacity=data.capacity||4;state.tubes=CRGame.clone(data.tubes);state.initialTubes=CRGame.clone(data.tubes);state.rules=data.rules||{};state.ruleState=CRGame.createRuleState(state.tubes,state.capacity,state.rules);state.initialRuleState=CRGame.cloneRuleState(state.ruleState);state.moveLimit=data.moveLimit||null;state.selectedTube=null;state.moveCount=0;state.history=[];state.isAnimating=false;state.isChoosingDye=false;state.isCleared=false;state.isStuck=false;state.isLimitFailed=false;tutorialStep=0;
    $('#clear-modal').classList.remove('open');$('#stuck-modal').classList.remove('open');$('#limit-modal').classList.remove('open');
    var w=CRStage.worldFor(id),world=$('#world'),total=CR_STAGES.length,done=worldCompletion(w);world.className='world '+w.key;world.style.setProperty('--gray',(100-(done.total?done.count/done.total*100:0))+'%');$('#world-name').textContent=w.name;$('#stage-number').textContent=id;$('#stage-total').textContent=total;$('#rule-chip').textContent=stageRuleLabel(data);$('.level-progress').setAttribute('aria-label','全'+total+'レベル中、現在レベル'+id);
    render();show('game-screen');updateTutorial();
  }
  function makeTube(i){
    var tube=state.tubes[i],el=document.createElement('button'),locked=CRGame.isTubeLocked(state.rules,state.ruleState,i),chainStep=CRGame.chainStepForTube(state.rules,i),isLock=(state.rules.lockedTubes||[]).indexOf(i)>=0||!!chainStep,target=state.rules.targets&&state.rules.targets[i],portal=CRGame.portalForTube(state.rules,i),serve=CRGame.serveForTube(state.rules,state.ruleState,i);
    el.className='tube capacity-'+state.capacity+(state.selectedTube===i?' selected':'')+(locked?' locked-tube':'')+(isLock&&!locked?' unlocked-tube':'')+(target?' target-tube target-'+target:'')+(portal?' portal-'+portal.role+' portal-pair-'+portal.pairIndex:'')+(serve?' serve-tube serve-lane-'+serve.laneIndex+(serve.current?'':' serve-done'):'');el.dataset.index=i;
    var label='チューブ '+(i+1)+'、ボール '+tube.length+'個',grayCount=tube.filter(function(color){return color==='gray';}).length;if(grayCount)label+='、無色球 '+grayCount+'個';if(tube[tube.length-1]==='gray')label+='、最上段は無色';if(locked)label+='、ロック中';if(chainStep&&locked)label+='、連鎖'+(chainStep.index+1)+'段目、'+colorName(chainStep.color)+'完成で解放';if(target)label+='、目標 '+colorName(target);if(portal)label+='、ポータル'+portal.symbol+(portal.role==='entry'?'入口、出口はチューブ'+(portal.exit+1):'出口、入口はチューブ'+(portal.entry+1));if(serve)label+='、出荷ドック'+serve.symbol+'、出荷'+serve.served+'/'+serve.total+(serve.current?'、注文'+colorName(serve.current.target):'、全便完了');el.setAttribute('aria-label',label);if(locked)el.setAttribute('aria-disabled','true');
    if(isLock){var lock=document.createElement('span');lock.className='lock-badge';lock.setAttribute('aria-hidden','true');lock.textContent=locked?'🔒':'🔓';el.appendChild(lock);}
    if(chainStep&&locked){var condition=document.createElement('span');condition.className='unlock-condition condition-'+chainStep.color;condition.textContent=(chainStep.index+1)+'段 '+colorName(chainStep.color);el.appendChild(condition);}
    if(target){var marker=document.createElement('span');marker.className='target-marker';marker.setAttribute('aria-hidden','true');marker.textContent='◎';el.appendChild(marker);}
    if(portal){var badge=document.createElement('span'),symbol=document.createElement('b'),role=document.createElement('small');badge.className='portal-badge';badge.setAttribute('aria-hidden','true');symbol.textContent=portal.symbol;role.textContent=portal.role==='entry'?'IN ↓':'OUT ↑';badge.appendChild(symbol);badge.appendChild(role);el.appendChild(badge);}
    if(serve){var serveBadge=document.createElement('span'),serveSymbol=document.createElement('b'),serveTarget=document.createElement('small');serveBadge.className='serve-badge';serveBadge.setAttribute('aria-hidden','true');serveSymbol.textContent='📦 '+serve.symbol;serveTarget.textContent=serve.current?colorName(serve.current.target)+' ORDER':'DONE';serveBadge.appendChild(serveSymbol);serveBadge.appendChild(serveTarget);el.appendChild(serveBadge);}
    for(var p=0;p<state.capacity;p++){var ball=document.createElement('i');ball.className='ball'+(p<tube.length?' '+tube[p]:' empty');ball.style.setProperty('--slot',p);el.appendChild(ball);}
    var pointerAt=0;el.addEventListener('pointerup',function(e){if(e.pointerType==='mouse'&&e.button!==0)return;pointerAt=Date.now();e.preventDefault();tapTube(i);});el.addEventListener('click',function(){if(Date.now()-pointerAt<500)return;tapTube(i);});return el;
  }
  function updateCounters(){
    $('#move-count').textContent=state.moveCount;$('#best-count').textContent=save.bestMoves[state.stageId]?'BEST '+save.bestMoves[state.stageId]:'BEST —';$('#undo-btn').disabled=!state.history.length||state.isAnimating;
    var limit=$('#limit-count');if(state.moveLimit){limit.textContent='残り '+Math.max(0,state.moveLimit-state.moveCount)+'手';limit.classList.remove('hidden');}else{limit.textContent='';limit.classList.add('hidden');}
    var forgeArea=$('#forge-area'),forge=$('#forge-btn'),forgeLimit=state.rules.forgeLimit||0;if(forgeLimit){forgeArea.classList.remove('hidden');forge.disabled=state.isAnimating||state.isCleared||state.ruleState.forgeRemaining<=0;$('#forge-count').textContent='残り'+state.ruleState.forgeRemaining+'回';forge.setAttribute('aria-label','選択した無色球を染色、残り'+state.ruleState.forgeRemaining+'回');}else{forgeArea.classList.add('hidden');forge.disabled=true;closeForgePicker();}
    var flip=$('#flip-btn'),flipLimit=state.rules.flipLimit||0;if(flipLimit){flip.classList.remove('hidden');flip.disabled=state.isAnimating||state.isChoosingDye||state.isCleared||!CRGame.canFlip(state.rules,state.ruleState);$('#flip-count').textContent='残り'+state.ruleState.flipsRemaining+'回・SIDE '+(state.ruleState.isFlipped?'B':'A');flip.setAttribute('aria-label','盤面を上下反転、残り'+state.ruleState.flipsRemaining+'回、現在SIDE '+(state.ruleState.isFlipped?'B':'A'));}else{flip.classList.add('hidden');flip.disabled=true;}renderServeQueue();
  }
  function updateSelection(previous){if(previous!==null&&board.children[previous])board.children[previous].classList.remove('selected');if(state.selectedTube!==null&&board.children[state.selectedTube])board.children[state.selectedTube].classList.add('selected');requestAnimationFrame(drawPortalLines);}
  function updateTube(i){var old=board.children[i];if(old)board.replaceChild(makeTube(i),old);}
  function drawPortalLines(){
    var svg=$('#portal-lines'),pairs=CRGame.portalPairs(state.rules);svg.innerHTML='';if(!pairs.length){svg.classList.add('hidden');return;}var world=$('#world'),rect=world.getBoundingClientRect();if(!rect.width||!rect.height)return;svg.classList.remove('hidden');svg.setAttribute('viewBox','0 0 '+rect.width+' '+rect.height);pairs.forEach(function(pair,index){var entry=board.children[pair.entry],exit=board.children[pair.exit];if(!entry||!exit)return;var a=entry.getBoundingClientRect(),b=exit.getBoundingClientRect(),x1=a.left+a.width/2-rect.left,y1=a.top+a.height*.55-rect.top,x2=b.left+b.width/2-rect.left,y2=b.top+b.height*.55-rect.top,path=document.createElementNS('http://www.w3.org/2000/svg','path'),bend=Math.max(22,Math.abs(x2-x1)*.2);path.setAttribute('d','M '+x1+' '+y1+' Q '+((x1+x2)/2)+' '+(Math.min(y1,y2)-bend)+' '+x2+' '+y2);path.setAttribute('class','portal-line portal-pair-'+index);path.dataset.pairIndex=index;svg.appendChild(path);});
  }
  function render(){board.innerHTML='';board.classList.toggle('capacity-5',state.capacity===5);board.classList.toggle('side-b',!!state.ruleState.isFlipped);state.tubes.forEach(function(_,i){board.appendChild(makeTube(i));});updateCounters();var data=CR_STAGES[state.stageId-1];if(data)$('#rule-chip').textContent=stageRuleLabel(data);requestAnimationFrame(drawPortalLines);}
  function updateTutorial(){var t=$('#tutorial'),icon=t.querySelector('span'),text=t.querySelector('b'),help=t.querySelector('small'),selected=state.selectedTube===null?null:state.tubes[state.selectedTube];if(state.stageId===1&&!save.tutorialCompleted){t.classList.remove('hidden');icon.textContent='☝';text.textContent=tutorialStep?'移動先の筒をタップ':'この筒をタップ';help.textContent='空の筒か同じ色の上へ1個移動しよう';}else if(state.stageId===61&&state.ruleState.flipsUsed===0){t.classList.remove('hidden');icon.textContent='↕';text.textContent='新操作 FLIP';help.textContent=state.moveCount?'FLIPで底と上を入れ替えよう':'まず青を空の筒へ1個移動';}else if(state.stageId===66&&state.ruleState.dyesUsed===0){t.classList.remove('hidden');icon.textContent='⚗';text.textContent='新操作 COLOR FORGE';if(state.isChoosingDye)help.textContent='赤に染める結果を確認して決定';else if(selected&&selected[selected.length-1]==='gray')help.textContent='COLOR FORGEをタップ';else if(state.moveCount===0)help.textContent='無色球「?」を空の筒へ移動';else help.textContent='トップの無色球「?」を選択';}else if(state.stageId===71&&state.moveCount<2){t.classList.remove('hidden');icon.textContent='◉';text.textContent='新経路 PORTAL A';help.textContent=state.moveCount?'筒2の黄を入口Aへ送ろう':'まず筒2の赤を出口Aへ移動';}else if(state.stageId===76&&CRGame.servedCount(state.rules,state.ruleState)===0){t.classList.remove('hidden');icon.textContent='📦';text.textContent='新目標 SORT & SERVE';help.textContent='DOCK Aで赤を4個そろえると自動出荷';}else t.classList.add('hidden');}
  function openForge(){
    if(state.isAnimating||state.isCleared||state.isLimitFailed||!state.rules.forgeLimit)return;clearHint();
    var tube=state.selectedTube;if(tube===null||!state.tubes[tube].length||state.tubes[tube][state.tubes[tube].length-1]!=='gray'){if(tube!==null)invalid(tube);else CRSound.invalid();toast('トップの無色球「?」を選んでください');return;}
    var choices=CRGame.dyeChoices(state.tubes,tube,state.rules,state.ruleState);if(!choices.length){invalid(tube);toast('この無色球は染色できません');return;}
    cancelSolve();state.isChoosingDye=true;var options=$('#forge-options'),needs=CRGame.dyeNeeds(state.tubes,state.rules);options.innerHTML='';choices.forEach(function(color){var button=document.createElement('button'),name=document.createElement('b'),detail=document.createElement('small'),needed=needs[color]||0,stock=Math.max(0,state.rules.dyeStock[color]-(state.ruleState.dyeUsed[color]||0));button.className='forge-color '+color;button.dataset.color=color;name.textContent=colorName(color)+'に染める';detail.textContent=needed?'完成にあと'+needed+'・顔料'+stock:'完成数は充足・顔料'+stock;button.setAttribute('aria-label',colorName(color)+'に染める。'+detail.textContent);button.appendChild(name);button.appendChild(detail);button.onclick=function(){dyeSelected(color);};options.appendChild(button);});
    $('#forge-picker').classList.remove('hidden');$('#forge-btn').setAttribute('aria-expanded','true');updateCounters();updateTutorial();
  }
  function dyeSelected(color){
    var tube=state.selectedTube;if(!state.isChoosingDye||tube===null||CRGame.dyeChoices(state.tubes,tube,state.rules,state.ruleState).indexOf(color)<0)return;
    clearHint();cancelSolve();state.history.push({tubes:CRGame.clone(state.tubes),ruleState:CRGame.cloneRuleState(state.ruleState),moveCount:state.moveCount});if(state.history.length>100)state.history.shift();state.isAnimating=true;closeForgePicker();var serveBefore=(state.ruleState.serveProgress||[]).slice();CRGame.applyDye(state.tubes,tube,color,state.capacity,state.rules,state.ruleState);var serveEvents=collectServeEvents(serveBefore);state.moveCount++;state.selectedTube=null;render();var tubeEl=board.children[tube],balls=tubeEl.querySelectorAll('.ball'),ball=serveEvents.length?null:balls[state.tubes[tube].length-1],serveEl=animateServeEvents(serveEvents);tubeEl.classList.add('forging-tube');if(ball)ball.classList.add('forging-ball');$('#forge-btn').classList.add('forging');CRSound.move();updateTutorial();toast(serveEvents.length?serveEventText(serveEvents[0]):'⚗ 無色球 → '+colorName(color));
    var finished=false;function finish(){if(finished)return;finished=true;state.isAnimating=false;tubeEl.classList.remove('forging-tube');if(ball)ball.classList.remove('forging-ball');clearServeEvents(serveEvents);$('#forge-btn').classList.remove('forging');updateCounters();var data=CR_STAGES[state.stageId-1];if(data)$('#rule-chip').textContent=stageRuleLabel(data);if(CRGame.isCleared(state.tubes,state.capacity,state.rules,state.ruleState))clearStage();else if(state.moveLimit&&state.moveCount>=state.moveLimit)showLimit();else checkSolvability();}
    if(serveEl||ball)(serveEl||ball).addEventListener('animationend',finish,{once:true});setTimeout(finish,serveEvents.length?560:460);
  }
  function checkSolvability(){
    cancelSolve();if(state.isCleared||state.isLimitFailed)return;
    if(CRGame.isStuck(state.tubes,state.capacity,state.rules,state.ruleState)){showStuck();return;}
    var generation=solveGeneration,key=currentKey(),search=CRGame.createSolveSearch(state.tubes,state.capacity,searchOptions(50000)),started=Date.now();
    function slice(){
      if(generation!==solveGeneration||state.isCleared||state.isLimitFailed||key!==currentKey())return;
      var sliceStarted=Date.now(),result='searching';while(result==='searching'&&Date.now()-sliceStarted<6)result=search.step(200);
      if(result==='unsolvable'){showStuck();return;}
      if(result==='unknown'||result==='solvable'||Date.now()-started>=1200)return;
      solveTimer=setTimeout(slice,0);
    }
    solveTimer=setTimeout(slice,0);
  }
  function tapTube(i){
    if(state.isAnimating||state.isCleared||state.isLimitFailed)return;if(state.isChoosingDye){CRSound.invalid();toast('色を選ぶかキャンセルしてください');return;}clearHint();
    if(CRGame.isTubeLocked(state.rules,state.ruleState,i)){invalid(i);var step=CRGame.chainStepForTube(state.rules,i);toast(step?'🔒 '+colorName(step.color)+'を完成すると使えます':'🔒 1色完成すると使えます');return;}
    if(state.selectedTube===null){if(!state.tubes[i].length){invalid(i);return;}state.selectedTube=i;tutorialStep=1;updateSelection(null);updateTutorial();return;}
    if(state.selectedTube===i){var deselected=state.selectedTube;state.selectedTube=null;updateSelection(deselected);return;}
    var from=state.selectedTube,portalOut=CRGame.portalExit(state.rules,i),portal=portalOut>=0?CRGame.portalForTube(state.rules,i):null;if(!CRGame.isLegalMove(state.tubes,from,i,state.capacity,state.rules,state.ruleState)){invalid(i);if(portalOut>=0&&state.tubes[portalOut].length>=state.capacity)toast('ポータル'+portal.symbol+'の出口が満杯です');return;}
    cancelSolve();state.history.push({tubes:CRGame.clone(state.tubes),ruleState:CRGame.cloneRuleState(state.ruleState),moveCount:state.moveCount});if(state.history.length>100)state.history.shift();state.isAnimating=true;
    var locksWereOpen=state.ruleState.locksOpen,chainBefore=state.ruleState.chainIndex||0,serveBefore=(state.ruleState.serveProgress||[]).slice();CRGame.applyMove(state.tubes,from,i,state.capacity,state.rules,state.ruleState);var serveEvents=collectServeEvents(serveBefore),openedLegacy=!locksWereOpen&&state.ruleState.locksOpen,openedChain=(state.ruleState.chainIndex||0)>chainBefore,openedNow=openedLegacy||openedChain,unlockedStep=openedChain&&state.rules.unlockChain[chainBefore];state.moveCount++;state.selectedTube=null;
    if(openedNow)render();else{updateTube(from);updateTube(i);if(portalOut>=0)updateTube(portalOut);serveEvents.forEach(function(event){updateTube(event.tube);});updateCounters();}drawPortalLines();
    var fromEl=board.children[from],toEl=board.children[i],receiveEl=portalOut>=0?board.children[portalOut]:toEl,portalBall=null,portalLine=portal?$('#portal-lines [data-pair-index="'+portal.pairIndex+'"]'):null,serveEl=animateServeEvents(serveEvents),finished=false;fromEl.classList.add('pouring');if(portalOut>=0){toEl.classList.add('portal-entering');receiveEl.classList.add('portal-exiting');var balls=receiveEl.querySelectorAll('.ball');portalBall=serveEvents.length?null:balls[state.tubes[portalOut].length-1];if(portalBall)portalBall.classList.add('warping-ball');if(portalLine)portalLine.classList.add('active');toast('◉ PORTAL '+portal.symbol+' → 筒'+(portalOut+1));}else receiveEl.classList.add('receiving');if(unlockedStep)toast('🔓 '+colorName(unlockedStep.color)+'完成・筒'+(unlockedStep.tube+1)+'解放');else if(openedLegacy)toast('🔓 チューブを解放しました');if(serveEvents.length)toast(serveEventText(serveEvents[0]));if(!save.tutorialCompleted){save.tutorialCompleted=true;persist();}CRSound.move();updateTutorial();
    function finish(){if(finished)return;finished=true;state.isAnimating=false;fromEl.classList.remove('pouring');toEl.classList.remove('receiving','portal-entering');receiveEl.classList.remove('receiving','portal-exiting');if(portalBall)portalBall.classList.remove('warping-ball');if(portalLine)portalLine.classList.remove('active');clearServeEvents(serveEvents);updateCounters();if(CRGame.isCleared(state.tubes,state.capacity,state.rules,state.ruleState))clearStage();else if(state.moveLimit&&state.moveCount>=state.moveLimit)showLimit();else checkSolvability();}
    (serveEl||portalBall||fromEl).addEventListener('animationend',finish,{once:true});setTimeout(finish,serveEvents.length?560:portalOut>=0?430:220);
  }
  function flipBoard(){
    if(state.isAnimating||state.isChoosingDye||state.isCleared||state.isLimitFailed)return;clearHint();
    if(!CRGame.canFlip(state.rules,state.ruleState)){CRSound.invalid();toast('FLIPはもう使えません');return;}
    cancelSolve();var previous=state.selectedTube;state.selectedTube=null;updateSelection(previous);state.history.push({tubes:CRGame.clone(state.tubes),ruleState:CRGame.cloneRuleState(state.ruleState),moveCount:state.moveCount});if(state.history.length>100)state.history.shift();state.isAnimating=true;CRGame.applyFlip(state.tubes,state.rules,state.ruleState);state.moveCount++;render();board.classList.add('flipping');CRSound.move();updateTutorial();toast('↕ SIDE '+(state.ruleState.isFlipped?'B':'A')+'へ反転');
    var finished=false;function finish(){if(finished)return;finished=true;board.classList.remove('flipping');state.isAnimating=false;updateCounters();var data=CR_STAGES[state.stageId-1];if(data)$('#rule-chip').textContent=stageRuleLabel(data);if(CRGame.isCleared(state.tubes,state.capacity,state.rules,state.ruleState))clearStage();else if(state.moveLimit&&state.moveCount>=state.moveLimit)showLimit();else checkSolvability();}
    board.addEventListener('animationend',finish,{once:true});setTimeout(finish,520);
  }
  function invalid(i){CRSound.invalid();var el=board.children[i];if(!el)return;el.classList.remove('shake');void el.offsetWidth;el.classList.add('shake');if(navigator.vibrate&&save.vibration)navigator.vibrate(35);}
  function hideStuck(){state.isStuck=false;$('#stuck-modal').classList.remove('open');}
  function showStuck(){clearHint();closeForgePicker();state.isStuck=true;var previous=state.selectedTube;state.selectedTube=null;updateSelection(previous);$('#stuck-modal').classList.add('open');}
  function hideLimit(){state.isLimitFailed=false;$('#limit-modal').classList.remove('open');}
  function showLimit(){clearHint();state.isLimitFailed=true;var previous=state.selectedTube;state.selectedTube=null;updateSelection(previous);$('#limit-modal').classList.add('open');}
  function undo(){if(state.isAnimating||state.isCleared||!state.history.length)return;cancelWork();hideStuck();hideLimit();var old=state.history.pop();state.tubes=CRGame.clone(old.tubes);state.ruleState=CRGame.cloneRuleState(old.ruleState);state.moveCount=old.moveCount;state.selectedTube=null;render();updateTutorial();}
  function restart(){if(state.isAnimating)return;cancelWork();hideStuck();hideLimit();state.tubes=CRGame.clone(state.initialTubes);state.ruleState=CRGame.cloneRuleState(state.initialRuleState);state.moveCount=0;state.history=[];state.selectedTube=null;state.isCleared=false;state.isStuck=false;state.isLimitFailed=false;$('#clear-modal').classList.remove('open');render();updateTutorial();}
  function hint(){
    if(state.isAnimating||state.isCleared||state.isLimitFailed)return;
    cancelWork();var previous=state.selectedTube;state.selectedTube=null;updateSelection(previous);
    if(state.isStuck||CRGame.isStuck(state.tubes,state.capacity,state.rules,state.ruleState)){showStuck();return;}
    var generation=solveGeneration,key=currentKey(),job=CRHint.search(state.tubes,state.capacity,searchOptions(50000)),started=Date.now();
    function slice(){
      if(generation!==solveGeneration||key!==currentKey()||state.isCleared||state.isLimitFailed)return;
      var sliceStarted=Date.now(),result={status:'searching'};while(result.status==='searching'&&Date.now()-sliceStarted<6)result=job.step(200);
      if(result.status==='searching'&&Date.now()-started<1200){solveTimer=setTimeout(slice,0);return;}
      if(result.status!=='solved'||!result.move){toast('HINTを計算できません');return;}
      if(state.moveLimit&&result.distance>state.moveLimit-state.moveCount)toast('残り手数ではクリアできません');
      if(result.move.type==='flip'){var flip=$('#flip-btn');flip.classList.add('hint-flip');toast('HINT：↕ FLIP');setTimeout(function(){if(generation===solveGeneration)flip.classList.remove('hint-flip');},700);return;}
      if(result.move.type==='dye'){var dyeTube=board.children[result.move.tube],forge=$('#forge-btn');dyeTube.classList.add('hint-from');forge.classList.add('hint-forge');toast('HINT：筒'+(result.move.tube+1)+'の無色球 → '+colorName(result.move.color));setTimeout(function(){if(generation===solveGeneration){dyeTube.classList.remove('hint-from');forge.classList.remove('hint-forge');}},700);return;}
      var portalOut=CRGame.portalExit(state.rules,result.move.to),portal=portalOut>=0?CRGame.portalForTube(state.rules,result.move.to):null,hintBoard=CRGame.clone(state.tubes),hintState=CRGame.cloneRuleState(state.ruleState),hintBefore=(hintState.serveProgress||[]).slice();CRGame.applyMove(hintBoard,result.move.from,result.move.to,state.capacity,state.rules,hintState);var hintServe=null;CRGame.serveLanes(state.rules).some(function(lane,laneIndex){if((hintState.serveProgress[laneIndex]||0)>(hintBefore[laneIndex]||0)){hintServe={lane:lane,laneIndex:laneIndex,batch:serveBatches(lane)[hintBefore[laneIndex]||0]};return true;}return false;});if(hintServe){var serveSource=board.children[result.move.from],serveEntry=board.children[result.move.to],serveReceive=board.children[portalOut>=0?portalOut:result.move.to],serveCard=$('.serve-lane[data-lane-index="'+hintServe.laneIndex+'"]'),serveLine=portal?$('#portal-lines [data-pair-index="'+portal.pairIndex+'"]'):null;serveSource.classList.add('hint-from');serveEntry.classList.add('hint-to');serveReceive.classList.add('hint-serve');if(serveCard)serveCard.classList.add('hint-serve');if(serveLine)serveLine.classList.add('active');toast('HINT：筒'+(result.move.from+1)+(portal?' → PORTAL '+portal.symbol:'')+' → DOCK '+(hintServe.lane.symbol||String.fromCharCode(65+hintServe.laneIndex))+'で'+colorName(hintServe.batch.target)+'を出荷');setTimeout(function(){if(generation===solveGeneration){serveSource.classList.remove('hint-from');serveEntry.classList.remove('hint-to');serveReceive.classList.remove('hint-serve');if(serveCard)serveCard.classList.remove('hint-serve');if(serveLine)serveLine.classList.remove('active');}},760);return;}if(portalOut>=0){var source=board.children[result.move.from],entry=board.children[result.move.to],exit=board.children[portalOut],line=$('#portal-lines [data-pair-index="'+portal.pairIndex+'"]');source.classList.add('hint-from');entry.classList.add('hint-to');exit.classList.add('hint-to');if(line)line.classList.add('active');toast('HINT：筒'+(result.move.from+1)+' → PORTAL '+portal.symbol+' → 筒'+(portalOut+1));setTimeout(function(){if(generation===solveGeneration){source.classList.remove('hint-from');entry.classList.remove('hint-to');exit.classList.remove('hint-to');if(line)line.classList.remove('active');}},700);return;}
      var a=board.children[result.move.from],b=board.children[result.move.to];a.classList.add('hint-from');hintTimer=setTimeout(function(){if(generation===solveGeneration)b.classList.add('hint-to');},120);setTimeout(function(){if(generation===solveGeneration){a.classList.remove('hint-from');b.classList.remove('hint-to');}},650);
    }
    solveTimer=setTimeout(slice,0);
  }
  function confetti(){var box=$('#confetti');box.innerHTML='';for(var i=0;i<28;i++){var x=document.createElement('i');x.style.left=(5+Math.random()*90)+'%';x.style.background=['#ff5d73','#ffd447','#36c9a5','#518cff','#9b65d8'][i%5];x.style.animationDelay=(Math.random()*.35)+'s';box.appendChild(x);}setTimeout(function(){box.innerHTML='';},1900);}
  function clearStage(){cancelWork();state.isCleared=true;var total=CR_STAGES.length;save.clearedStages.indexOf(state.stageId)<0&&save.clearedStages.push(state.stageId);if(state.stageId<total)save.unlockedStage=Math.max(save.unlockedStage,state.stageId+1);var best=save.bestMoves[state.stageId];if(!best||state.moveCount<best)save.bestMoves[state.stageId]=state.moveCount;persist();$$('.tube').forEach(function(t){t.classList.add('complete');});CRSound.clear();confetti();$('#result-moves').textContent=state.moveCount;$('#result-best').textContent=save.bestMoves[state.stageId];$('#next-btn').textContent=state.stageId===total?'ALL STAGES CLEAR':'NEXT STAGE';setTimeout(function(){$('#clear-modal').classList.add('open');},850);}
  function toast(s){var t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(function(){t.classList.remove('show');},1400);}

  $('#play-btn').onclick=function(){loadStage(Math.min(save.unlockedStage,CR_STAGES.length));};$('#select-btn').onclick=function(){buildSelect();show('select-screen');};$$('.back-title').forEach(function(b){b.onclick=function(){cancelWork();show('title-screen');};});$('#home-btn').onclick=function(){if(state.isAnimating)return;cancelWork();buildSelect();show('select-screen');};$('#undo-btn').onclick=undo;$('#restart-btn').onclick=restart;$('#forge-btn').onclick=openForge;$('#forge-cancel-btn').onclick=function(){closeForgePicker();updateCounters();updateTutorial();};$('#flip-btn').onclick=flipBoard;$('#stuck-undo-btn').onclick=undo;$('#stuck-restart-btn').onclick=restart;$('#limit-undo-btn').onclick=undo;$('#limit-restart-btn').onclick=restart;$('#hint-btn').onclick=hint;$('#replay-btn').onclick=restart;$('#modal-select-btn').onclick=function(){cancelWork();buildSelect();show('select-screen');};$('#next-btn').onclick=function(){if(state.stageId<CR_STAGES.length)loadStage(state.stageId+1);else{buildSelect();show('select-screen');$('#clear-modal').classList.remove('open');}};
  window.addEventListener('resize',drawPortalLines);app.loadStage=loadStage;app.undo=undo;app.restart=restart;app.forge=openForge;app.flip=flipBoard;app.hint=hint;app.complete=clearStage;buildSelect();
}());
