(function(){
'use strict';
var $=function(s){return document.querySelector(s);}, $$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s));};
var save=CRStorage.load();
var state={stageId:1,capacity:4,tubes:[],initialTubes:[],selectedTube:null,moveCount:0,history:[],isAnimating:false,isCleared:false,isStuck:false};
var app=window.ColorRestore={save:save,state:state};
var screens=$$('.screen'),board=$('#tube-board'),tutorialStep=0,hintTimer;
function show(id){screens.forEach(function(x){x.classList.toggle('active',x.id===id);});window.scrollTo(0,0);}
function persist(){CRStorage.save(save);}
function worldCompletion(worldKey){var range=worldKey==='garden'?[1,10]:worldKey==='ocean'?[11,20]:[21,30],n=0;save.clearedStages.forEach(function(x){if(x>=range[0]&&x<=range[1])n++;});return n;}
function buildSelect(){var worlds=[['Garden',1],['Ocean',11],['City',21]];$('#world-tabs').innerHTML=worlds.map(function(w){return '<button data-start="'+w[1]+'">'+w[0]+'<small>'+worldCompletion(w[0].toLowerCase())+'/10</small></button>';}).join('');var html='';CR_STAGES.forEach(function(s){var locked=s.id>save.unlockedStage,done=save.clearedStages.indexOf(s.id)>=0;html+='<button class="stage-tile '+(locked?'locked ':'')+(done?'done':'')+'" data-stage="'+s.id+'" '+(locked?'disabled':'')+'><span>'+(locked?'🔒':s.id)+'</span><small>'+(done?'BEST '+save.bestMoves[s.id]:locked?'LOCKED':'PLAY')+'</small></button>';});$('#stage-grid').innerHTML=html;$$('.stage-tile:not(.locked)').forEach(function(b){b.onclick=function(){loadStage(+b.dataset.stage);};});$$('#world-tabs button').forEach(function(b){b.onclick=function(){var tile=$('[data-stage="'+b.dataset.start+'"]');if(tile)tile.scrollIntoView({behavior:'smooth',block:'center'});};});}
function loadStage(id){var data=CR_STAGES[id-1];if(!data||id>save.unlockedStage)return;state.stageId=id;state.capacity=4;state.tubes=CRGame.clone(data.tubes);state.initialTubes=CRGame.clone(data.tubes);state.selectedTube=null;state.moveCount=0;state.history=[];state.isAnimating=false;state.isCleared=false;state.isStuck=false;tutorialStep=0;$('#clear-modal').classList.remove('open');$('#stuck-modal').classList.remove('open');var w=CRStage.worldFor(id),world=$('#world'),total=CR_STAGES.length;world.className='world '+w.key;world.style.setProperty('--gray',(100-worldCompletion(w.key)*10)+'%');$('#world-name').textContent=w.name;$('#stage-number').textContent=id;$('#stage-total').textContent=total;$('.level-progress').setAttribute('aria-label','全'+total+'レベル中、現在レベル'+id);render();show('game-screen');updateTutorial();}
function makeTube(i){var tube=state.tubes[i],el=document.createElement('button');el.className='tube'+(state.selectedTube===i?' selected':'');el.dataset.index=i;el.setAttribute('aria-label','チューブ '+(i+1)+'、ボール '+tube.length+'個');for(var p=0;p<state.capacity;p++){var ball=document.createElement('i');ball.className='ball'+(p<tube.length?' '+tube[p]:' empty');ball.style.setProperty('--slot',p);el.appendChild(ball);}var pointerAt=0;el.addEventListener('pointerup',function(e){if(e.pointerType==='mouse'&&e.button!==0)return;pointerAt=Date.now();e.preventDefault();tapTube(i);});el.addEventListener('click',function(){if(Date.now()-pointerAt<500)return;tapTube(i);});return el;}
function updateCounters(){$('#move-count').textContent=state.moveCount;$('#best-count').textContent=save.bestMoves[state.stageId]?'BEST '+save.bestMoves[state.stageId]:'BEST —';$('#undo-btn').disabled=!state.history.length||state.isAnimating;}
function updateSelection(previous){if(previous!==null&&board.children[previous])board.children[previous].classList.remove('selected');if(state.selectedTube!==null&&board.children[state.selectedTube])board.children[state.selectedTube].classList.add('selected');}
function updateTube(i){var old=board.children[i];if(old)board.replaceChild(makeTube(i),old);}
function render(){board.innerHTML='';state.tubes.forEach(function(_,i){board.appendChild(makeTube(i));});updateCounters();}
function updateTutorial(){var t=$('#tutorial');if(state.stageId===1&&!save.tutorialCompleted){t.classList.remove('hidden');t.querySelector('b').textContent=tutorialStep?'移動先の筒をタップ':'この筒をタップ';}else t.classList.add('hidden');}
function tapTube(i){if(state.isAnimating||state.isCleared)return;if(state.selectedTube===null){if(!state.tubes[i].length){invalid(i);return;}state.selectedTube=i;tutorialStep=1;updateSelection(null);updateTutorial();return;}if(state.selectedTube===i){var deselected=state.selectedTube;state.selectedTube=null;updateSelection(deselected);return;}var from=state.selectedTube;if(!CRGame.isLegalMove(state.tubes,from,i,state.capacity)){invalid(i);return;}state.history.push({tubes:CRGame.clone(state.tubes),moveCount:state.moveCount});if(state.history.length>100)state.history.shift();state.isAnimating=true;CRGame.applyMove(state.tubes,from,i,state.capacity);state.moveCount++;state.selectedTube=null;updateTube(from);updateTube(i);updateCounters();var fromEl=board.children[from],toEl=board.children[i],finished=false;fromEl.classList.add('pouring');toEl.classList.add('receiving');if(!save.tutorialCompleted){save.tutorialCompleted=true;persist();}CRSound.move();updateTutorial();function finish(){if(finished)return;finished=true;state.isAnimating=false;fromEl.classList.remove('pouring');toEl.classList.remove('receiving');updateCounters();if(CRGame.isCleared(state.tubes,state.capacity))clearStage();else if(CRGame.isStuck(state.tubes,state.capacity))showStuck();}fromEl.addEventListener('animationend',finish,{once:true});setTimeout(finish,220);}
function invalid(i){CRSound.invalid();var el=board.children[i];el.classList.remove('shake');void el.offsetWidth;el.classList.add('shake');if(navigator.vibrate&&save.vibration)navigator.vibrate(35);}
function hideStuck(){state.isStuck=false;$('#stuck-modal').classList.remove('open');}
function showStuck(){state.isStuck=true;state.selectedTube=null;updateSelection(null);$('#stuck-modal').classList.add('open');}
function undo(){if(state.isAnimating||state.isCleared||!state.history.length)return;hideStuck();var old=state.history.pop();state.tubes=CRGame.clone(old.tubes);state.moveCount=old.moveCount;state.selectedTube=null;render();}
function restart(){if(state.isAnimating)return;hideStuck();state.tubes=CRGame.clone(state.initialTubes);state.moveCount=0;state.history=[];state.selectedTube=null;state.isCleared=false;state.isStuck=false;$('#clear-modal').classList.remove('open');render();}
function hint(){if(state.isAnimating||state.isCleared)return;if(state.isStuck||CRGame.isStuck(state.tubes,state.capacity)){showStuck();return;}var h=CRHint.choose(state.tubes,state.capacity);if(!h){toast('動かせるボールがありません');return;}clearTimeout(hintTimer);var a=board.children[h.from],b=board.children[h.to];a.classList.add('hint-from');setTimeout(function(){b.classList.add('hint-to');},120);hintTimer=setTimeout(function(){a.classList.remove('hint-from');b.classList.remove('hint-to');},650);}
function confetti(){var box=$('#confetti');box.innerHTML='';for(var i=0;i<28;i++){var x=document.createElement('i');x.style.left=(5+Math.random()*90)+'%';x.style.background=['#ff5d73','#ffd447','#36c9a5','#518cff','#9b65d8'][i%5];x.style.animationDelay=(Math.random()*.35)+'s';box.appendChild(x);}setTimeout(function(){box.innerHTML='';},1900);}
function clearStage(){state.isCleared=true;save.clearedStages.indexOf(state.stageId)<0&&save.clearedStages.push(state.stageId);if(state.stageId<30)save.unlockedStage=Math.max(save.unlockedStage,state.stageId+1);var best=save.bestMoves[state.stageId];if(!best||state.moveCount<best)save.bestMoves[state.stageId]=state.moveCount;persist();$$('.tube').forEach(function(t){t.classList.add('complete');});CRSound.clear();confetti();$('#result-moves').textContent=state.moveCount;$('#result-best').textContent=save.bestMoves[state.stageId];$('#next-btn').textContent=state.stageId===30?'ALL STAGES CLEAR':'NEXT STAGE';setTimeout(function(){$('#clear-modal').classList.add('open');},850);}
function toast(s){var t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(function(){t.classList.remove('show');},1400);}
$('#play-btn').onclick=function(){loadStage(Math.min(save.unlockedStage,30));};$('#select-btn').onclick=function(){buildSelect();show('select-screen');};$$('.back-title').forEach(function(b){b.onclick=function(){show('title-screen');};});$('#home-btn').onclick=function(){if(state.isAnimating)return;buildSelect();show('select-screen');};$('#undo-btn').onclick=undo;$('#restart-btn').onclick=restart;$('#stuck-undo-btn').onclick=undo;$('#stuck-restart-btn').onclick=restart;$('#hint-btn').onclick=hint;$('#replay-btn').onclick=restart;$('#modal-select-btn').onclick=function(){buildSelect();show('select-screen');};$('#next-btn').onclick=function(){if(state.stageId<30)loadStage(state.stageId+1);else{buildSelect();show('select-screen');$('#clear-modal').classList.remove('open');}};
app.loadStage=loadStage;app.undo=undo;app.restart=restart;app.hint=hint;app.complete=clearStage;buildSelect();
}());
