'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert'),{execFileSync}=require('child_process');
const context={window:{}};vm.createContext(context);
for(const file of ['js/game.js','js/hint.js','data/stages.js','data/advanced-stages.js','data/progression.js','data/flip-stages.js','data/forge-stages.js','data/portal-stages.js','data/serve-stages.js','data/combo-stages.js','js/stage.js']){
  vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});context.CRGame=context.window.CRGame;
}
const G=context.window.CRGame,H=context.window.CRHint,stages=context.window.CR_STAGES,comboStages=stages.slice(80),plain=value=>JSON.parse(JSON.stringify(value));
function finish(job){let result;do{result=job.step(5000);}while(result==='searching'||result.status==='searching');return result;}
function action(board,capacity,rules,ruleState,step){return step&&step.type==='flip'?G.applyFlip(board,rules,ruleState):G.applyMove(board,step[0],step[1],capacity,rules,ruleState);}
function inventory(board){const counts={};board.forEach(tube=>tube.forEach(color=>counts[color]=(counts[color]||0)+1));return counts;}
function after(stage,steps){const board=G.clone(stage.tubes),ruleState=G.createRuleState(board,stage.capacity,stage.rules);steps.forEach(step=>assert(action(board,stage.capacity,stage.rules,ruleState,step)>0));return {board,ruleState};}
function distance(board,capacity,rules,ruleState){const result=finish(H.search(board,capacity,{maxVisited:50000,rules,ruleState:G.cloneRuleState(ruleState)}));assert.equal(result.status,'solved');return result.distance;}

assert.equal(stages.length,85,'the complete game has 85 levels');
assert.deepEqual(comboStages.map(stage=>stage.id),[81,82,83,84,85],'COMBO FLOW ids are contiguous');
const worlds=context.window.CRStage.worlds(stages.length),comboWorld=worlds.at(-1);assert.equal(worlds.length,11,'eleven world tabs cover all levels');assert.deepEqual([comboWorld.key,comboWorld.start,comboWorld.end],['combo',81,85],'COMBO FLOW owns levels 81-85');

let previousMinimum=0;
comboStages.forEach(stage=>{
  const capacity=stage.capacity||4,rules=stage.rules,initialInventory=inventory(stage.tubes),board=G.clone(stage.tubes),ruleState=G.createRuleState(board,capacity,rules),flowMoves=[],flowCounts=[],earnedMoves=[],comboRuns=[];let run=[];
  assert.equal(stage.moveLimit,null,`level ${stage.id}: COMBO FLOW has no time or move limit`);assert(rules.comboThreshold>=2,`level ${stage.id}: combo threshold is explicit`);assert(rules.requiredFlows>=1,`level ${stage.id}: required FLOW count is explicit`);assert(stage.minimumMoves>previousMinimum,`level ${stage.id}: exact minimum rises`);previousMinimum=stage.minimumMoves;
  Object.values(initialInventory).forEach(count=>assert.equal(count,capacity,`level ${stage.id}: complete color inventory`));assert(!G.isCleared(board,capacity,rules,ruleState),`level ${stage.id}: FLOW goal prevents an early clear`);
  stage.solution.forEach((step,index)=>{
    const beforeBoard=G.clone(board),beforeState=G.cloneRuleState(ruleState);
    if(step&&step.type==='flip'){assert.equal(G.applyFlip(board,rules,ruleState),1,`level ${stage.id}: FLIP ${index+1}`);run=[];}
    else{
      const info=G.comboMoveInfo(board,step[0],step[1],capacity,rules,ruleState);assert(info,`level ${stage.id}: move ${index+1} is legal`);const moved=G.applyMove(board,step[0],step[1],capacity,rules,ruleState);assert.equal(moved,info.count,`level ${stage.id}: preview and actual count agree at ${index+1}`);
      if(info.usesFlow){const room=capacity-beforeBoard[step[1]].length,expected=Math.min(G.topRun(beforeBoard[step[0]]),room);assert.equal(moved,expected,`level ${stage.id}: FLOW respects run and capacity`);assert(moved>1,`level ${stage.id}: FLOW visibly moves a block`);flowMoves.push(index+1);flowCounts.push(moved);run=[];}else{assert.equal(moved,1,`level ${stage.id}: normal move ${index+1} moves one ball only`);if(info.qualifies){run=info.sameChain?run.concat(index+1):[index+1];if(info.earnsFlow){earnedMoves.push(index+1);comboRuns.push({color:info.color,moves:run.slice()});}}else run=[];}
      assert.equal(beforeBoard[step[0]].length-board[step[0]].length,moved,`level ${stage.id}: source loses the announced count`);assert.equal(board[step[1]].length-beforeBoard[step[1]].length,moved,`level ${stage.id}: destination gains the announced count`);assert.equal(ruleState.lastMoveCount,moved,`level ${stage.id}: moved count is stored for undo/UI`);assert(beforeState.flowReady===info.usesFlow,`level ${stage.id}: only a held FLOW enables a block move`);
    }
    assert.deepEqual(inventory(board),initialInventory,`level ${stage.id}: action ${index+1} preserves inventory`);board.forEach(tube=>assert(tube.length<=capacity,`level ${stage.id}: capacity remains valid`));
  });
  assert.equal(stage.solution.length,stage.verifiedMoves,`level ${stage.id}: certificate length`);assert.deepEqual(flowMoves,Array.from(stage.flowMoves),`level ${stage.id}: FLOW timing`);assert.deepEqual(flowCounts,Array.from(stage.flowCounts),`level ${stage.id}: FLOW moved counts`);assert.deepEqual(earnedMoves,Array.from(stage.flowEarnedMoves),`level ${stage.id}: FLOW charge timing`);assert.deepEqual(comboRuns,plain(stage.comboRuns),`level ${stage.id}: uninterrupted same-color runs`);assert.equal(ruleState.flowsUsed,rules.requiredFlows,`level ${stage.id}: required FLOW operations are used`);assert(G.isCleared(board,capacity,rules,ruleState),`level ${stage.id}: certificate clears`);
  const exact=finish(H.search(stage.tubes,capacity,{maxVisited:50000,rules,ruleState:G.createRuleState(stage.tubes,capacity,rules)}));assert.equal(exact.status,'solved',`level ${stage.id}: production Hint solves initial state`);assert.equal(exact.distance,stage.minimumMoves,`level ${stage.id}: production BFS proves exact minimum`);
});

const normalBoard=[['blue','red','red','red'],[]],normalRules={comboThreshold:2,requiredFlows:1},normalState=G.createRuleState(normalBoard,4,normalRules);assert.equal(G.applyMove(normalBoard,0,1,4,normalRules,normalState),1,'a top run still moves one ball before FLOW');assert.deepEqual(plain(normalBoard),[['blue','red','red'],['red']]);
const capacityBoard=[['red','red','red'],['red','red','red']],capacityState=G.createRuleState(capacityBoard,4,normalRules);capacityState.flowReady=true;capacityState.comboGauge=2;capacityState.comboColor='red';assert.equal(G.flowMoveCount(capacityBoard,0,1,4,normalRules,capacityState),1,'FLOW preview clips to one open slot');assert.equal(G.applyMove(capacityBoard,0,1,4,normalRules,capacityState),1,'FLOW never exceeds capacity');assert.equal(capacityBoard[1].length,4);
const previewBoard=[['red'],['red'],['blue'],['blue'],[]],previewState=G.createRuleState(previewBoard,4,normalRules);previewState.comboGauge=1;previewState.comboColor='red';const keep=G.comboMoveInfo(previewBoard,0,1,4,normalRules,previewState),change=G.comboMoveInfo(previewBoard,2,3,4,normalRules,previewState),empty=G.comboMoveInfo(previewBoard,0,4,4,normalRules,previewState);assert(keep.earnsFlow&&keep.nextGauge===2,'same-color continuation earns FLOW');assert.equal(change.breakReason,'color','switching the moved color is previewed as a break');assert.equal(change.nextGauge,1,'a color switch starts the new chain at one');assert.equal(empty.breakReason,'empty','an empty destination is previewed as a reset');assert.equal(empty.nextGauge,0);

const level81=comboStages[0],ready81=after(level81,level81.solution.slice(0,2)),snapshot81={board:G.clone(ready81.board),state:G.cloneRuleState(ready81.ruleState)};assert(ready81.ruleState.flowReady,'level 81 earns FLOW after two consecutive moves');const readyHint=finish(H.search(ready81.board,4,{maxVisited:50000,rules:level81.rules,ruleState:ready81.ruleState}));assert(readyHint.move.flow&&readyHint.move.count===2,'Hint announces a two-ball FLOW move');G.applyMove(ready81.board,readyHint.move.from,readyHint.move.to,4,level81.rules,ready81.ruleState);assert.equal(ready81.ruleState.flowsUsed,1);ready81.board.splice(0,ready81.board.length,...G.clone(snapshot81.board));Object.assign(ready81.ruleState,G.cloneRuleState(snapshot81.state));assert.deepEqual(plain(ready81.board),plain(snapshot81.board),'Undo restores the pre-FLOW board');assert.deepEqual(plain(ready81.ruleState),plain(snapshot81.state),'Undo restores gauge, held FLOW, counts, and last move size');const waiting=G.cloneRuleState(ready81.ruleState);assert.deepEqual(plain(G.cloneRuleState(ready81.ruleState)),plain(waiting),'selection waiting does not mutate or expire FLOW');

const level82=comboStages[1],choice82=after(level82,level82.choicePrefix),optimalInfo=G.comboMoveInfo(choice82.board,...level82.optimalFlowMove,4,level82.rules,choice82.ruleState),decoyInfo=G.comboMoveInfo(choice82.board,...level82.decoyFlowMove,4,level82.rules,choice82.ruleState);assert(optimalInfo.usesFlow&&decoyInfo.usesFlow,'level 82 exposes multiple FLOW destinations');const optimal82={board:G.clone(choice82.board),state:G.cloneRuleState(choice82.ruleState)},decoy82={board:G.clone(choice82.board),state:G.cloneRuleState(choice82.ruleState)};G.applyMove(optimal82.board,...level82.optimalFlowMove,4,level82.rules,optimal82.state);G.applyMove(decoy82.board,...level82.decoyFlowMove,4,level82.rules,decoy82.state);assert.equal(distance(decoy82.board,4,level82.rules,decoy82.state)-distance(optimal82.board,4,level82.rules,optimal82.state),level82.decoyPenalty,'level 82 rewards the displayed optimal FLOW destination');

const level83=comboStages[2],charged83=after(level83,level83.breakPrefix),breakInfo=G.comboMoveInfo(charged83.board,...level83.breakMove,4,level83.rules,charged83.ruleState);assert.equal(charged83.ruleState.comboGauge,2,'level 83 reaches two of three charges');assert.equal(breakInfo.breakReason,'color','level 83 decoy visibly switches color');const broken83={board:G.clone(charged83.board),state:G.cloneRuleState(charged83.ruleState)};G.applyMove(broken83.board,...level83.breakMove,4,level83.rules,broken83.state);assert.equal(1+distance(broken83.board,4,level83.rules,broken83.state)-(level83.minimumMoves-level83.breakPrefix.length),level83.breakPenalty,'breaking level 83 combo costs two moves');
assert.equal(comboStages[3].rules.requiredFlows,2,'level 84 requires two FLOW uses');assert.deepEqual(Array.from(comboStages[3].flowCounts),[2,3],'level 84 moves two distinct blocks');
const level85=comboStages[4],noFlip=G.createRuleState(level85.tubes,4,level85.rules);noFlip.flipsRemaining=0;assert.equal(finish(G.createSolveSearch(level85.tubes,4,{maxVisited:50000,rules:level85.rules,ruleState:noFlip})),'unsolvable','level 85 requires FLIP as well as FLOW');const beforeFlip85=after(level85,level85.solution.slice(0,7)),flipSnapshot=G.cloneRuleState(beforeFlip85.ruleState);assert(flipSnapshot.comboGauge>0&&!flipSnapshot.flowReady);G.applyFlip(beforeFlip85.board,level85.rules,beforeFlip85.ruleState);assert.equal(beforeFlip85.ruleState.comboGauge,0,'FLIP resets a charging combo');Object.assign(beforeFlip85.ruleState,G.cloneRuleState(flipSnapshot));assert.deepEqual(plain(beforeFlip85.ruleState),plain(flipSnapshot),'Undo restores the pre-FLIP combo state');

const keyRules={comboThreshold:3,requiredFlows:2},keyBoard=[['red'],['red'],[]],baseKeyState=G.createRuleState(keyBoard,4,keyRules),gaugeState=G.cloneRuleState(baseKeyState),readyState=G.cloneRuleState(baseKeyState),usedState=G.cloneRuleState(baseKeyState);gaugeState.comboGauge=1;gaugeState.comboColor='red';readyState.comboGauge=3;readyState.comboColor='red';readyState.flowReady=true;usedState.flowsUsed=1;assert.notEqual(G.stateKey(keyBoard,4,keyRules,baseKeyState),G.stateKey(keyBoard,4,keyRules,gaugeState),'stateKey includes combo gauge and color');assert.notEqual(G.stateKey(keyBoard,4,keyRules,gaugeState),G.stateKey(keyBoard,4,keyRules,readyState),'stateKey includes held FLOW');assert.notEqual(G.stateKey(keyBoard,4,keyRules,baseKeyState),G.stateKey(keyBoard,4,keyRules,usedState),'stateKey includes required FLOW progress');

const generated=execFileSync(process.execPath,['tools/find-combo-levels.js'],{encoding:'utf8'}).trim().split('\n').filter(Boolean).map(line=>JSON.parse(line));assert.deepEqual(generated,plain(comboStages),'published COMBO FLOW data matches the deterministic production-rule generator');
const html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('js/app.js','utf8'),css=fs.readFileSync('css/style.css','utf8'),sound=fs.readFileSync('js/sound.js','utf8'),data=fs.readFileSync('data/combo-stages.js','utf8'),generator=fs.readFileSync('tools/find-combo-levels.js','utf8');assert(html.includes('id="combo-area"')&&html.includes('data/combo-stages.js?v=20260913-2')&&html.includes('<span id="stage-total">85</span>'),'gauge UI, stage data, and total are loaded');assert(app.includes("text='FLOW ×'+info.count")&&app.includes("text='RESET'")&&app.includes("text='色替え 1/"),'destinations preview moved count and break conditions');assert(app.includes("receiveBalls[ballIndex].classList.add('flow-ball')")&&app.includes('CRSound.flow(moved)'),'block movement has light and sound feedback');assert(app.includes('save.vibration')&&sound.includes('ColorRestore.save.sound'),'feedback honors vibration and sound settings');assert(app.includes('result.move.flow')||app.includes('hintFlow.usesFlow'),'Hint exposes FLOW moved counts');assert(app.includes('ruleState:CRGame.cloneRuleState(state.ruleState)')&&app.includes('state.ruleState=CRGame.cloneRuleState(state.initialRuleState)'),'Undo and Restart snapshot complete FLOW state');assert(css.includes('.combo-track')&&css.includes('@keyframes flowBall')&&css.includes('@media(max-width:370px){.combo .tube-board'),'gauge, block animation, and 360px layout are explicit');assert(!data.includes('Math.random'),'COMBO FLOW has no hidden randomness');assert(generator.includes('off.flow')&&generator.includes('decoyPenalty')&&generator.includes("noFlip.status!=='unsolvable'"),'generator proves FLOW, choice cost, and final FLIP necessity');

const saved80={unlockedStage:80,clearedStages:Array.from({length:80},(_,i)=>i+1),bestMoves:{'80':21},sound:true,vibration:true,tutorialCompleted:true,progressionVersion:3},storageContext={window:{CR_STAGES:stages},localStorage:{getItem:()=>JSON.stringify(saved80),setItem:()=>{}}};vm.createContext(storageContext);vm.runInContext(fs.readFileSync('js/storage.js','utf8'),storageContext,{filename:'js/storage.js'});const migrated=storageContext.window.CRStorage.load();assert.equal(migrated.unlockedStage,81,'players who cleared level 80 receive level 81');assert.equal(migrated.bestMoves['80'],21,'existing level 80 BEST survives');

console.log('COMBO FLOW levels 81-85: exact minima, previews, block capacity, required FLOW, two-use and FLIP finale, UI, undo, and save migration passed');
