#!/usr/bin/env node
'use strict';
const fs = require('fs');
const path = require('path');
const {analyzeAll} = require('./level-analyzer');

const ROOT = path.resolve(__dirname, '..');
const stateLimitArg = process.argv.find(arg => arg.startsWith('--state-limit='));
const stateLimit = stateLimitArg ? Number(stateLimitArg.split('=')[1]) : 5000;
const results = analyzeAll({stateLimit});
const json = JSON.stringify({generatedBy: 'node tools/analyze-levels.js', capacity: 4, stateLimit, levels: results}, null, 2) + '\n';
const header = '| Level | World | Colors | Tubes (empty) | Solvable | Shortest / certificate | States | Dead ends | Initial moves | Path avg branch | Score | Band | Notes |';
const rows = results.map(r => `| ${r.level} | ${r.world} | ${r.colors} | ${r.tubes} (${r.emptyTubes}) | yes | ${r.shortestMoves ?? '?'} / ${r.solutionMoves} | ${r.sampledStates} | ${r.observedDeadEnds} | ${r.initialLegalMoves} | ${r.averageSolutionBranching.toFixed(2)} | ${r.difficultyScore.toFixed(1)} | ${r.band} | ${r.notes} |`);
const markdown = `# Level analysis\n\n> Generated by \`node tools/analyze-levels.js --state-limit=${stateLimit}\`. Certificates are replayed upper bounds; exhaustive breadth-first traversal also supplies exact shortest distances. All transitions use production \`CRGame.isLegalMove\` and \`CRGame.applyMove\`. Tube-order normalization removes interchangeable positions.\n\n${header}\n|---:|---|---:|---:|---|---:|---:|---:|---:|---:|---:|---|---|\n${rows.join('\n')}\n\n## Interpretation\n\nDifficulty is a relative 0–100 engineering score combining exact shortest length when exhaustive (otherwise certificate length, at 0.8/move), color count (3.2/color), branching on the certified route, alternative legal moves, empty-tube usage, and a 12-point workspace-scarcity premium for one-buffer boards. Forced moves and moves that dismantle an already completed tube reduce the score. The JSON companion contains every component, including forced-move ratio, alternative moves per step, empty-tube dependency, maximum/average branching, and terminal dead ends.\n\nWhen the graph is exhausted, breadth-first traversal proves the shortest distance and terminal dead-end count for the complete normalized reachable graph. If a future level hits the state cap, these become bounded observations. Large exploration remains in this development-only Node tool and is never loaded by the browser.\n`;

fs.mkdirSync(path.join(ROOT, 'docs'), {recursive: true});
fs.writeFileSync(path.join(ROOT, 'docs/level-analysis.json'), json);
fs.writeFileSync(path.join(ROOT, 'docs/level-analysis.md'), markdown);
console.log(`analyzed ${results.length} levels (${results.reduce((n, r) => n + r.sampledStates, 0)} sampled states)`);
